[build]
builder = "nixpacks"
watchPatterns = [
  "/backend/**",
  "/packages/cli/**",
  "/packages/nibgate/**",
  "/packages/internal/**",
  "/package.json",
  "/pnpm-lock.yaml",
  "/pnpm-workspace.yaml"
]

[deploy]
startCommand = "pnpm start"
