// Export object storage — the hub's R2 bucket, same conventions as hub media
// (see backend/src/server/lib/nibgate-provider.js). Exports are generated by
// this service but stored in the shared bucket, so a finished deliverable can
// be fetched by URL instead of inlined into an API response.
//
// Configuration is the shared R2_* set. When it is absent (or the SDK is not
// installed), callers fall back to base64 in the JSON response; R2 is an
// optimization for large/binary deliverables, not a correctness requirement.
let s3 = null;
let sdk = null;

export function r2Config(env = process.env) {
  const endpoint = env.R2_ENDPOINT;
  const accessKeyId = env.R2_ACCESS_KEY_ID;
  const secretAccessKey = env.R2_SECRET_ACCESS_KEY;
  const bucket = env.R2_BUCKET;
  const publicUrl = (env.R2_PUBLIC_URL || '').replace(/\/+$/, '');
  if (!endpoint || !accessKeyId || !secretAccessKey || !bucket || !publicUrl) return null;
  return { endpoint, accessKeyId, secretAccessKey, bucket, publicUrl };
}

export function isR2Configured(env = process.env) {
  return Boolean(r2Config(env));
}

async function client(cfg) {
  // Lazy so a deployment without the SDK (or without R2) never pays for it.
  if (!sdk) sdk = await import('@aws-sdk/client-s3');
  if (!s3) {
    s3 = new sdk.S3Client({
      region: 'auto',
      endpoint: cfg.endpoint,
      credentials: { accessKeyId: cfg.accessKeyId, secretAccessKey: cfg.secretAccessKey },
    });
  }
  return { s3, PutObjectCommand: sdk.PutObjectCommand };
}

/**
 * Put one object. Returns { storageRef, url }. Throws when R2 is not
 * configured (callers should check isR2Configured first).
 */
export async function putExport({ key, body, contentType = 'application/octet-stream', cacheControl }) {
  const cfg = r2Config();
  if (!cfg) throw new Error('R2 is not configured (R2_ENDPOINT/R2_ACCESS_KEY_ID/R2_SECRET_ACCESS_KEY/R2_BUCKET/R2_PUBLIC_URL)');
  const { s3: c, PutObjectCommand } = await client(cfg);
  await c.send(new PutObjectCommand({
    Bucket: cfg.bucket,
    Key: key,
    Body: body,
    ContentType: contentType,
    CacheControl: cacheControl || 'private, max-age=0',
  }));
  return { storageRef: key, url: `${cfg.publicUrl}/${key}` };
}