const { install, connectSellerFlow, bodyText, SEL_PK, BUY_PK } = require('../harness/prod-lib.js');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chromium' });
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await ctx.newPage();
  page.setDefaultTimeout(30000);
  await install({ page, pk: SEL_PK });
  await page.goto('https://nibgate.xyz/share/mine', { waitUntil: 'commit' });
  await page.waitForTimeout(2000);
  await connectSellerFlow(page, { label: 'm', log: () => {} });
  await page.waitForTimeout(2500);
  const draftsBtn = page.locator('button').filter({ hasText: /Drafts/ }).first();
  console.log('drafts btn count:', await draftsBtn.count());
  await draftsBtn.click({ force: true });
  await page.waitForTimeout(1800);
  console.log('after Drafts click:', (await bodyText(page)).slice(0, 320).replace(/\n+/g, ' | '));
  const rows = await page.locator('div[role="row"], article, [class*="post" i], [class*="row" i]').count();
  console.log('row-ish containers:', rows);
  await browser.close();
})().catch((e) => { console.error('FAIL', e); process.exit(1); });
