const { bodyText } = require('../harness/prod-lib.js');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chromium' });
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await ctx.newPage();
  page.setDefaultTimeout(30000);
  const f = require('./fixtures.json');
  await page.goto(`https://nibgate.xyz/ns/${f.free.slug}`, { waitUntil: 'commit' });
  await page.waitForTimeout(3000);
  console.log('FREE:'); console.log((await bodyText(page)).replace(/\n+/g, ' | ').slice(0, 300));
  await page.goto('https://catwalk.nibgate.xyz', { waitUntil: 'commit' });
  await page.waitForTimeout(2500);
  const link = page.locator('a[href*="/blog/"], a[href*="/docs/"]').first();
  const href = await link.getAttribute('href').catch(() => '');
  await link.click().catch(() => {});
  await page.waitForTimeout(2500);
  console.log('SUB click ->', href);
  console.log('SUB:'); console.log((await bodyText(page)).replace(/\n+/g, ' | ').slice(0, 300));
  await browser.close();
})().catch((e) => { console.error('FAIL', e); process.exit(1); });
