const { install, connectSellerFlow, bodyText, BUY_PK, SEL_PK } = require('../harness/prod-lib.js');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chromium' });
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await ctx.newPage();
  page.setDefaultTimeout(30000);
  await install({ page, pk: BUY_PK });
  const f = require('./fixtures.json');
  await page.goto(`https://nibgate.xyz/ns/${f.paid.slug}`, { waitUntil: 'commit' });
  await page.waitForTimeout(2500);
  await connectSellerFlow(page, { label: 'b', log: () => {} });
  await page.waitForTimeout(2000);
  const b = await bodyText(page);
  console.log('GATE:', b.slice(0, 360).replace(/\n+/g, ' | '));
  console.log('stars in html:', await page.locator('text=/★|☆/').count());
  const explore = await (async () => { await page.goto('https://nibgate.xyz/explore', { waitUntil: 'commit' }); await page.waitForTimeout(3000); return page.locator('button').evaluateAll((els) => els.map((e) => e.innerText.trim().slice(0, 16)).filter(Boolean).filter((t) => /All|Writing|Articles|Essays|Newsletters|Media|Images|Music|Photos|Video/i.test(t)).slice(0, 12)); })();
  console.log('explore type buttons:', JSON.stringify(explore));
  await browser.close();
})().catch((e) => { console.error('FAIL', e); process.exit(1); });
