export default {
  index: "Nibgate Docs",
  "---overview": {
    type: "separator",
    title: "Overview",
  },
  overview: "What is Nibgate?",
  architecture: "Architecture",
  lifecycle: "End-to-end lifecycle",
  "agent-discovery": "Agent discovery",
  reputation: "Reputation",
  "---platform": {
    type: "separator",
    title: "Creator Platform",
  },
  "create-subblog": "Create a Subblog",
  "content-types": "Content Types",
  "image-optimization": "Image optimization",
  encryption: "Content encryption",
  "discovery-seo": "Discovery & SEO",
  nibshare: "Nibshare (quick-share)",
  "---setup": {
    type: "separator",
    title: "Setup",
  },
  "quick-start": "Quick start",
  "install-package": "Install package",
  "content-structures": "Content structures",
  widget: "Hub widget",
  "verify-site": "Verify a site",
  "---data": {
    type: "separator",
    title: "Data bridge",
  },
  "content-events": "Content events",
  "analytics-events": "Analytics events",
  "payments-receipts": "Payments and receipts",
  revenue: "Revenue & leaderboards",
  "---reference": {
    type: "separator",
    title: "Reference",
  },
  "api-reference": "API reference",
  examples: "Examples",
  roadmap: "Roadmap",
};
