const { install, makeWallet } = require('/Users/fortune/Documents/Workflows/nibgate-repo/e2e/harness/prod-lib.js');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chromium' });
  const page = await browser.newPage();
  page.setDefaultTimeout(45000);
  page.on('console', (m) => { if (/error/i.test(m.text()) && m.text().length < 200) console.log('[console]', m.type(), m.text().slice(0,180)); });
  page.on('requestfailed', (r) => console.log('[reqfail]', r.url().slice(0,90), r.failure()?.errorText));
  await page.goto('https://nibgate.xyz/share', { waitUntil: 'commit', timeout: 45000 });
  await page.waitForTimeout(3000);
  const body = await page.locator('body').innerText();
  console.log('BODY:\n' + body.split('\n').filter(l=>l.trim()).slice(0,40).join('\n'));
  console.log('BUTTONS:', await page.getByRole('button').allInnerTexts().catch(()=>[]));
  const w = await makeWallet('0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d');
  await install({ page, wallet: w.wallet });
  console.log('wallet installed');
  await page.waitForTimeout(1500);
  const body2 = await page.locator('body').innerText();
  console.log('BODY2:\n' + body2.split('\n').filter(l=>l.trim()).slice(0,40).join('\n'));
  const connect = page.getByText(/connect wallet/i).first();
  console.log('connect count:', await connect.count());
  await connect.click().catch(()=>console.log('click connect failed'));
  await page.waitForTimeout(2000);
  const body3 = await page.locator('body').innerText();
  console.log('BODY3 (after connect click):\n' + body3.split('\n').filter(l=>l.trim()).slice(0,40).join('\n'));
  await browser.close();
})().catch(e=>{ console.error('ERR', e.message); process.exit(1); });
