export type DocPage = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  sections: Array<{
    title: string;
    body: string;
    code?: string;
    bullets?: string[];
  }>;
};

export const docPages: DocPage[] = [
  {
    slug: "quick-start",
    eyebrow: "Start here",
    title: "Quick start",
    description: "Connect a wallet, register a site, paste the widget, install the package, and start sending content plus unlock events to Nibgate.",
    sections: [
      { title: "1. Connect wallet", body: "Your wallet is the creator identity. It owns the profile, connected sites, content dashboard, analytics, and earnings views." },
      { title: "2. Register your site", body: "Add the exact origin where protected content lives. Nibgate returns a site id and verification token." },
      { title: "3. Paste the widget", body: "The widget verifies ownership and streams page activity from the verified domain.", code: `<script async src="https://nibgate.xyz/widget.js"\n  data-nibgate-site="site_..."\n  data-nibgate-token="ngv_...">\n</script>` },
      { title: "4. Install the package", body: "The package belongs in the creator app. It controls gating, pricing, content metadata, unlock events, and receipt reporting.", code: "npm install nibgate" }
    ]
  },
  {
    slug: "install-package",
    eyebrow: "Package",
    title: "Install the Nibgate package",
    description: "Use the package inside the app that owns the paid content. The package is the unlock and event bridge, not just a metrics helper.",
    sections: [
      { title: "Install", body: "Install the package from npm once it is published. During local development, the repo can link the package from packages/nibgate.", code: "npm install nibgate" },
      { title: "What it does", body: "The package gates content, defines prices, records unlock attempts, and sends content plus receipt events to the Nibgate backend.", bullets: ["Protect article, image, music, and video resources.", "Keep receiver/payment config inside the creator site.", "Report public metadata without exposing protected content."] },
      { title: "What it should not do", body: "Do not put backend secrets in browser code. Any privileged signing or server-only event submission should happen from your own backend or trusted server route." }
    ]
  },
  {
    slug: "widget",
    eyebrow: "Widget",
    title: "Hub widget",
    description: "The widget is the simple ownership and analytics bridge. Creators paste one script into their site and Nibgate can verify the origin.",
    sections: [
      { title: "Snippet", body: "Use the site id and token generated by the dashboard.", code: `<script async src="https://nibgate.xyz/widget.js"\n  data-nibgate-site="site_..."\n  data-nibgate-token="ngv_...">\n</script>` },
      { title: "Responsibilities", body: "The widget proves the domain can serve Nibgate's verification token and can stream browser-side activity signals.", bullets: ["Page views", "Content impressions", "Route activity", "Widget health checks"] },
      { title: "Not a replacement for the package", body: "The widget should not be the payment brain. Gating and unlock logic belongs in the package running inside the creator site." }
    ]
  },
  {
    slug: "verify-site",
    eyebrow: "Verification",
    title: "Verify a site",
    description: "A site starts pending, becomes verified when the widget is found, and can be rechecked to make sure the widget still exists.",
    sections: [
      { title: "Pending", body: "After registration, the dashboard shows setup instructions and a verification token. The site should not be trusted for Explore until verified." },
      { title: "Verified", body: "The crawler checks the homepage for the widget/site token. Once found, Nibgate can accept content and metrics from that origin." },
      { title: "Ongoing health", body: "If a creator removes the widget later, the backend should mark verification stale after scheduled checks and stop accepting public discovery events until it returns." }
    ]
  },
  {
    slug: "content-events",
    eyebrow: "Content",
    title: "Send content metadata",
    description: "Content metadata tells Nibgate what paid resources exist without copying the protected resource itself.",
    sections: [
      { title: "Supported types", body: "Nibgate's public content types are intentionally simple: article, image, music, and video.", bullets: ["article", "image", "music", "video"] },
      { title: "Minimum payload", body: "Send a stable external id, type, title, URL, price, currency, tags, and optional preview image.", code: `nibgate.content.upsert({\n  externalId: "post_123",\n  type: "article",\n  title: "Paid research note",\n  url: "https://creator.com/research",\n  price: "2.00",\n  currency: "USDC",\n  tags: ["research", "ai"]\n})` },
      { title: "Source of truth", body: "The creator site remains the source of truth. Nibgate stores metadata for search, analytics, and Explore." }
    ]
  },
  {
    slug: "analytics-events",
    eyebrow: "Analytics",
    title: "Track analytics events",
    description: "Analytics combines widget activity and package events into site, content, and route-level dashboards.",
    sections: [
      { title: "Page events", body: "The widget can track views, referrers, path, device hints, and time-on-page style signals." },
      { title: "Content events", body: "The package can report impressions, unlock starts, unlock completions, failed unlocks, and receipt references." },
      { title: "Dashboard metrics", body: "The creator dashboard should show timeline filters, traffic sources, top content, unlock conversion, and historical trends." }
    ]
  },
  {
    slug: "payments-receipts",
    eyebrow: "Payments",
    title: "Payments and receipts",
    description: "Nibgate earnings are payment analytics, not withdrawals. Funds should flow through the creator site's configured receiver.",
    sections: [
      { title: "Receiver config", body: "Each site can use its own receiver address. A creator may operate multiple sites with different payment destinations." },
      { title: "Receipt types", body: "Nibgate is designed around x402-style gateway receipts and Arc testnet transaction receipts while the payment rail matures." },
      { title: "Event payload", body: "Unlock completion events should include amount, currency, receiver, content id, transaction hash or gateway receipt id, and chain explorer URL when available." }
    ]
  },
  {
    slug: "api-reference",
    eyebrow: "API",
    title: "API reference",
    description: "The backend receives verification, content, analytics, and earnings events from the widget, package, and dashboard.",
    sections: [
      { title: "Status", body: "Use the status endpoint to confirm the service is online.", code: "GET https://api.nibgate.xyz/api/nibgate/status" },
      { title: "Site registration", body: "Dashboard APIs create sites, issue verification tokens, recheck widget health, and archive removed sites." },
      { title: "Event ingestion", body: "Widget and package event routes should reject unknown origins, removed sites, stale verification, and malformed content ids." }
    ]
  },
  {
    slug: "examples",
    eyebrow: "Examples",
    title: "Examples",
    description: "Common ways creators can use Nibgate for paid content and agent-readable resources.",
    sections: [
      { title: "Paid article", body: "Protect a premium article route, report article metadata, and stream unlock receipts into earnings." },
      { title: "Music drop", body: "Publish public metadata for a track, gate the full audio, and show unlock/conversion analytics in the dashboard." },
      { title: "Agent route", body: "Expose a paid API or data route that humans and AI agents can discover through verified metadata." }
    ]
  }
];

export const primaryDocs = docPages.map(({ slug, title }) => ({ slug, title }));

export function getDocPage(slug: string) {
  return docPages.find((page) => page.slug === slug);
}
